version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: demo-postgres
    env_file:
      - ./.env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d demo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network
    profiles:
      - dev
      - prod

  rabbitmq:
    image: rabbitmq:3-management
    container_name: demo-rabbitmq
    env_file:
      - ./.env.docker
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network
    profiles:
      - dev
      - prod

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-nestjs
    env_file:
      - ./.env.docker
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/graphql",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - prod

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq_data:
